### PR TITLE
Port direct IO operations to Arduino101

### PR DESCRIPTION
**Pull request by facchinm**

### CODE REVIEW

**Comment by sandeepmistry** [comment]
@PaulStoffregen Is there anything blocking this from being merged?

**Comment by PaulStoffregen** [comment]
Has anyone actually tested this code?  Even just 1 confirmation it worked on 1 board is enough.

**Comment by facchinm** [comment]
Hi Paul,
I'm adding @mbriden to the conversation so he can check the functionality with a live test setup. The code is a porting of https://github.com/01org/corelibs-arduino101/commit/4cf249987b5da85a90025d174021824e5ce09cc6 and compiles/runs correctly (but I don't know if the results are the expected ones)

**Comment by PaulStoffregen** [comment]
I recently got a 101 board, but so far I haven't had the time or a need to use it yet.

If nobody else can confirm this, I'll try to take a look next week.  At the moment I'm working on improvements to the Ethernet library.....

**Comment by PaulStoffregen** [comment]
Ok, I'm going to merge this without any testing.  But I must undo the PIN_TO_BASEREG change, because that breaks this library on every other board!  (can you see why I'm asking if anyone has tested this patch)

**Comment by PaulStoffregen** [comment]
Ok, I'm running it here right now.  Seems to work fairly well.  :)

**Pull request merged**
